Repository es3n1n/portal2-internal, pull requests merged in 2023-06, with the labels that each got.

#15 feat: removed asm math in place of std::
  portal2-internal/util/math/base.hpp
  portal2-internal/util/math/math.cpp
  portal2-internal/util/math/math.hpp
Labels: refactor

#16 #13: feat: added a safe_cast implementation
  portal2-internal/hack/cfg/cfg.cpp
  portal2-internal/portal2-internal.vcxproj
  portal2-internal/portal2-internal.vcxproj.filters
  portal2-internal/sdk/misc/color_t.hpp
  portal2-internal/util/cast/cast.hpp
  portal2-internal/util/game/game.cpp
  portal2-internal/util/math/base.hpp
  portal2-internal/util/math/math.cpp
  portal2-internal/util/util.hpp
Labels: enhancement

#14 v1.0.3
  .clang-format
  .gitattributes
  .gitignore
  CMakeLists.txt
  LICENSE
  cmake.toml
  cmake/cmkr.cmake
  msvc/portal2-internal.sln
  portal2-internal/hack/cfg/cfg.cpp
  portal2-internal/hack/cfg/cfg.hpp
  portal2-internal/hack/cfg/opts.hpp
  portal2-internal/hack/features/visuals/change_portal_colors.cpp
  portal2-internal/hack/menu/menu.cpp
  portal2-internal/portal2-internal.vcxproj
  portal2-internal/portal2-internal.vcxproj.filters
  portal2-internal/sdk/misc/client_class.hpp
  portal2-internal/sdk/misc/color_t.hpp
  portal2-internal/sdk/misc/flt_range_t.hpp
  portal2-internal/sdk/misc/vec_t.hpp
  portal2-internal/util/cast/cast.hpp
  portal2-internal/util/game/game.cpp
  portal2-internal/util/math/base.hpp
  portal2-internal/util/math/math.cpp
  portal2-internal/util/math/math.hpp
  portal2-internal/util/util.hpp
  readme.md
Labels: update
